import { Issue, User, CityMetrics, LeaderboardUser } from './types';

// Let's use Connaught Place, New Delhi area for map positioning
export const MAP_CENTER: [number, number] = [28.6304, 77.2177]; // New Delhi, India

export const initialIssues: Issue[] = [
  {
    id: 'issue-1',
    title: 'Severe Deep Pothole',
    type: 'pothole',
    severity: 'high',
    riskScore: 78,
    confidence: 96,
    department: 'Road & Highway Maintenance Dept',
    repairTime: '48 Hours',
    description: 'Deep, hazardous pothole near Janpath road crossing, Connaught Place. Creating a severe risk of tire damage and dangerous evasive maneuvers for motorcyclists and auto-rickshaws.',
    status: 'assigned',
    latitude: 28.6328,
    longitude: 77.2155,
    image: '/src/assets/images/severe_deep_pothole_1782758350443.jpg',
    reporterName: 'Amit Sharma',
    reporterEmail: 'amit.sharma@example.in',
    reportedAt: '2026-06-28T09:30:00Z',
    assignedOfficer: {
      name: 'Officer Sandeep Vardhan',
      dept: 'Roads & Asphalt Division',
      role: 'Chief Engineer',
      deadline: '2026-06-30T17:00:00Z'
    },
    inspectionReport: null,
    resourceAllocation: {
      teams: 1,
      budget: '₹90,000',
      equipment: ['Asphalt Roller', 'Tamping Machine', 'Warning Barriers'],
      assignedBudget: 90000,
      spentBudget: 45000
    },
    timeline: [
      { status: 'reported', timestamp: '2026-06-28T09:30:00Z', note: 'Issue submitted via mobile citizen application with image.', actor: 'Amit Sharma' },
      { status: 'ai_analyzed', timestamp: '2026-06-28T09:31:12Z', note: 'AI Vision classified issue: Pothole, High Severity, Risk 78/100.', actor: 'AI Core' },
      { status: 'assigned', timestamp: '2026-06-28T11:15:00Z', note: 'Assigned to Roads & Asphalt division. Scheduled repair crew deployment.', actor: 'Admin Sarika Joshi' }
    ],
    upvotes: 24,
    verifiedBy: ['user1@example.com', 'user2@example.com'],
    isEmergency: false,
    isDuplicateOf: null
  },
  {
    id: 'issue-2',
    title: 'Exposed High Voltage Wire',
    type: 'electrical_hazard',
    severity: 'urgent',
    riskScore: 95,
    confidence: 99,
    department: 'Electrical Grid & Power Authority',
    repairTime: 'Instant / Underway',
    description: 'Exposed, messy high voltage electrical cables hanging dangerously near public metro station exit. Sparks observed during damp weather conditions. Critical hazard to daily commuters!',
    status: 'in_progress',
    latitude: 28.6295,
    longitude: 77.2212,
    image: '/src/assets/images/exposed_voltage_wire_1782758365580.jpg', // representative lighting/wires
    reporterName: 'Deepak Mehra',
    reporterEmail: 'deepak.m@example.in',
    reportedAt: '2026-06-29T08:10:00Z',
    assignedOfficer: {
      name: 'Officer Alok Chaudhari',
      dept: 'Emergency Grid Response Team',
      role: 'Hazard Safety Supervisor',
      deadline: '2026-06-29T12:00:00Z'
    },
    inspectionReport: {
      inspectorName: 'Officer Alok Chaudhari',
      verifiedStatus: 'valid',
      notes: 'Confirmed live sparking wire cluster. Power successfully isolated from sector 4C. Commencing wire replacement.',
      timestamp: '2026-06-29T08:45:00Z'
    },
    resourceAllocation: {
      teams: 2,
      budget: '₹1,85,000',
      equipment: ['Insulated Crane Truck', 'Circuit Isolation Unit', 'New Cabling'],
      assignedBudget: 185000,
      spentBudget: 120000
    },
    timeline: [
      { status: 'reported', timestamp: '2026-06-29T08:10:00Z', note: 'URGENT Alert! Exposed sparking wire cluster reported on walkway.', actor: 'Deepak Mehra' },
      { status: 'ai_analyzed', timestamp: '2026-06-29T08:10:30Z', note: 'AI classified: CRITICAL ELECTRICAL HAZARD. Emergency mode activated. Dispatched alerts to Fire & Power stations.', actor: 'AI Emergency Core' },
      { status: 'assigned', timestamp: '2026-06-29T08:20:00Z', note: 'Emergency dispatch sent. Power Authority team on route.', actor: 'Admin Supervisor' },
      { status: 'inspection', timestamp: '2026-06-29T08:45:00Z', note: 'On-site verification completed. Confirmed wire isolated and safely secured.', actor: 'Officer Alok Chaudhari' },
      { status: 'in_progress', timestamp: '2026-06-29T09:00:00Z', note: 'Grid rewiring work has commenced.', actor: 'Officer Alok Chaudhari' }
    ],
    upvotes: 56,
    verifiedBy: ['deepak.m@example.in', 'user3@example.com', 'user4@example.com'],
    isEmergency: true,
    isDuplicateOf: null
  },
  {
    id: 'issue-3',
    title: 'Major Water Main Burst',
    type: 'water_leak',
    severity: 'high',
    riskScore: 72,
    confidence: 94,
    department: 'Water & Sanitation Dept',
    repairTime: '12 Hours',
    description: 'Clean drinking water is bursting at high pressure from a cracked main supply pipe, heavily flooding the street and disrupting regional water supply.',
    status: 'inspection',
    latitude: 28.6354,
    longitude: 77.2195,
    image: '/src/assets/images/major_water_burst_1782758382661.jpg',
    reporterName: 'Priya Patel',
    reporterEmail: 'priya.patel@example.in',
    reportedAt: '2026-06-29T05:22:00Z',
    assignedOfficer: {
      name: 'Officer Laxmi Dixit',
      dept: 'Hydraulics & Drainage Division',
      role: 'Hydraulic Specialist',
      deadline: '2026-06-29T20:00:00Z'
    },
    inspectionReport: {
      inspectorName: 'Officer Laxmi Dixit',
      verifiedStatus: 'valid',
      notes: 'Water leak verified. Main shut-off valve located. Temporary repair clamp required before full line restoration.',
      timestamp: '2026-06-29T09:30:00Z'
    },
    resourceAllocation: {
      teams: 1,
      budget: '₹1,40,000',
      equipment: ['Excavator', 'Water Sump Pump', 'Pipe Clamp Repair Kit'],
      assignedBudget: 140000,
      spentBudget: 80000
    },
    timeline: [
      { status: 'reported', timestamp: '2026-06-29T05:22:00Z', note: 'Water main burst reported on street sidewalk.', actor: 'Priya Patel' },
      { status: 'ai_analyzed', timestamp: '2026-06-29T05:23:00Z', note: 'AI Vision Analysis: Water leak, High Severity, Risk 72/100.', actor: 'AI Core' },
      { status: 'assigned', timestamp: '2026-06-29T07:30:00Z', note: 'Assigned to Water Hydraulics team.', actor: 'Admin Sarika Joshi' },
      { status: 'inspection', timestamp: '2026-06-29T09:30:00Z', note: 'Inspection team confirmed leak is active. Excavation planned.', actor: 'Officer Laxmi Dixit' }
    ],
    upvotes: 18,
    verifiedBy: ['sarika.j@example.in'],
    isEmergency: false,
    isDuplicateOf: null
  },
  {
    id: 'issue-4',
    title: 'Overflowing Public Waste Bin',
    type: 'garbage',
    severity: 'medium',
    riskScore: 45,
    confidence: 91,
    department: 'Waste & Sanitation Dept',
    repairTime: '24 Hours',
    description: 'Large public garbage bin is severely overflowing. Trash is scattering all over the roadside, attracting stray animals and blocking pedestrians.',
    status: 'reported',
    latitude: 28.6272,
    longitude: 77.2148,
    image: '/src/assets/images/overflowing_waste_bin_1782758400382.jpg',
    reporterName: 'Rajesh Kumar',
    reporterEmail: 'rajesh@example.in',
    reportedAt: '2026-06-29T09:55:00Z',
    assignedOfficer: null,
    inspectionReport: null,
    resourceAllocation: null,
    timeline: [
      { status: 'reported', timestamp: '2026-06-29T09:55:00Z', note: 'Overflowing public trash can reported on Sansad Marg.', actor: 'Rajesh Kumar' },
      { status: 'ai_analyzed', timestamp: '2026-06-29T09:56:10Z', note: 'AI classified: Garbage Overflow, Medium Severity, Risk 45/100. Department: Sanitation Dept.', actor: 'AI Core' }
    ],
    upvotes: 9,
    verifiedBy: [],
    isEmergency: false,
    isDuplicateOf: null
  },
  {
    id: 'issue-5',
    title: 'Completely Burnt Streetlight Row',
    type: 'street_light',
    severity: 'medium',
    riskScore: 50,
    confidence: 88,
    department: 'City Lighting & Power Dept',
    repairTime: '24 Hours',
    description: 'Three consecutive street lights are out on the Outer Circle corridor, creating a pitch-black walk path for pedestrians at night.',
    status: 'resolved',
    latitude: 28.6312,
    longitude: 77.2235,
    image: 'https://images.unsplash.com/photo-1509023464722-18d996393ca8?auto=format&fit=crop&q=80&w=600',
    reporterName: 'Aaradhya Mukherji',
    reporterEmail: 'aaradhya@example.in',
    reportedAt: '2026-06-27T21:10:00Z',
    assignedOfficer: {
      name: 'Officer Jagdish Patil',
      dept: 'Public Lighting Div',
      role: 'Senior Electrician',
      deadline: '2026-06-28T18:00:00Z'
    },
    inspectionReport: {
      inspectorName: 'Officer Jagdish Patil',
      verifiedStatus: 'valid',
      notes: 'Investigated and replaced blown fuses on pole line #12. Lights re-tested and operational.',
      timestamp: '2026-06-28T14:30:00Z'
    },
    resourceAllocation: {
      teams: 1,
      budget: '₹35,000',
      equipment: ['Bucket Truck', 'Standard Fuses', 'Heavy Duty LED Bulbs'],
      assignedBudget: 35000,
      spentBudget: 35000
    },
    timeline: [
      { status: 'reported', timestamp: '2026-06-27T21:10:00Z', note: 'Corridor streetlight outage reported.', actor: 'Aaradhya Mukherji' },
      { status: 'ai_analyzed', timestamp: '2026-06-27T21:11:00Z', note: 'AI Vision Analysis: Outage, Medium Severity, Risk 50/100.', actor: 'AI Core' },
      { status: 'assigned', timestamp: '2026-06-28T08:00:00Z', note: 'Assigned to Public Lighting team.', actor: 'Admin Sarika Joshi' },
      { status: 'in_progress', timestamp: '2026-06-28T13:00:00Z', note: 'Lighting crew on-site with bucket truck.', actor: 'Officer Jagdish Patil' },
      { status: 'resolved', timestamp: '2026-06-28T14:45:00Z', note: 'Outage resolved. All three lights illuminated successfully.', actor: 'Officer Jagdish Patil' }
    ],
    upvotes: 32,
    verifiedBy: ['aaradhya@example.in', 'user5@example.com', 'user6@example.com'],
    isEmergency: false,
    isDuplicateOf: null
  }
];

export const initialCityMetrics: CityMetrics = {
  healthScore: 84,
  roadsScore: 81,
  waterScore: 89,
  wasteScore: 78,
  electricityScore: 86,
  safetyScore: 85,
  resolvedCount: 342,
  activeCount: 4,
  totalSavedBudget: '₹28,50,000'
};

export const leaderboardData: LeaderboardUser[] = [
  { rank: 1, name: 'Amitabh Verma', xp: 2450, badgesCount: 12, resolvedIssues: 45 },
  { rank: 2, name: 'Anjali Deshmukh', xp: 1980, badgesCount: 9, resolvedIssues: 32 },
  { rank: 3, name: 'Sam.asakura0914', xp: 1540, badgesCount: 7, resolvedIssues: 24, isCurrentUser: true },
  { rank: 4, name: 'Deepak Mehra', xp: 1210, badgesCount: 5, resolvedIssues: 18 },
  { rank: 5, name: 'Karan Singhal', xp: 980, badgesCount: 4, resolvedIssues: 12 },
  { rank: 6, name: 'Sarika Joshi', xp: 850, badgesCount: 3, resolvedIssues: 9 },
  { rank: 7, name: 'Aaradhya Mukherji', xp: 720, badgesCount: 3, resolvedIssues: 8 }
];

export const translations = {
  en: {
    appName: 'Civic Taskforce AI',
    tagline: 'AI-Powered Hyperlocal Civic Issue Detection, Resolution & Smart Governance System',
    heroTitle: 'Report Civic Issues in Seconds using AI',
    heroDesc: 'Empower your community. Snap a picture, let AI classify and route the issue, and watch municipal teams resolve it in record time.',
    reportBtn: 'Report Problem',
    checkStatus: 'Check Status',
    nearbyIssues: 'Nearby Issues',
    heroStatsResolved: 'Issues Resolved',
    heroStatsActive: 'Active Reports',
    heroStatsSaved: 'Budget Optimizations',
    step1: '1. Click Photo',
    step2: '2. AI Detects Problem',
    step3: '3. Authorities Fix It',
    step1Desc: 'Upload or capture an image of the civic damage.',
    step2Desc: 'Gemini AI analyzes type, risk, and routing instantly.',
    step3Desc: 'Auto-routed to correct municipal team for rapid action.',
    dashboard: 'Dashboard',
    mapView: 'Interactive Map',
    leaderboard: 'Leaderboard',
    aiCopilot: 'AI Copilot Chat',
    municipality: 'Municipality Panel',
    activeUser: 'Active Citizen Profile',
    xpPoints: 'Civic Hero XP',
    badgesEarned: 'Badges Earned',
    reportNewIssue: 'Report a New Civic Issue',
    issueType: 'Issue Classification',
    severity: 'Severity Level',
    riskScore: 'Public Risk Score',
    department: 'Department Routing',
    location: 'Pin Location',
    explanation: 'AI Assessment Notes',
    submitReport: 'Submit Verified Report',
    duplicateFound: 'Duplicate Prevention system active!',
    duplicateMsg: 'A similar issue was detected nearby within 50 meters. Your details have been aggregated to prioritize this issue!',
    myReports: 'My Reported Issues',
    noReports: 'No reports submitted yet.',
    citizenFeedback: 'Community Verifications',
    verifyThisIssue: 'Verify / Confirm Issue',
    alreadyVerified: 'You verified this report',
    upvote: 'Upvote Report',
    welcomeBack: 'Welcome back, Civic Hero!',
    emergencyMode: 'EMERGENCY TRIGGER ACTIVE',
    emergencyDesc: 'Critical hazard detected. Emergency services have been auto-notified!',
    cityHealthScore: 'City Health Score',
    copilotPlaceholder: 'Ask Copilot: "Which area has high risk?" or "Is there flooding forecast?"',
    copilotTitle: 'Civic Smart Copilot',
    copilotTagline: 'Ask AI about dangerous zones, predictive maintenance, and city reports',
    predPotholes: 'Predictive Infrastructure Analysis',
    predFlood: 'AI Flood Zone Alerts',
    predGarbage: 'Predictive Refuse Overflow',
    officerDashboard: 'Officer Performance Rating',
    averageFixTime: 'Average Resolution Time',
    activeTeams: 'Active Service Crews',
    searchPlacePlaceholder: 'Search places in India to report issues...',
    searchBtn: 'Search',
    popularPlaces: 'Popular Places'
  },
  es: {
    appName: 'Civic Taskforce AI',
    tagline: 'Sistema de detección y resolución de problemas cívicos hiperlocales por IA',
    heroTitle: 'Reporte Problemas Cívicos en Segundos con IA',
    heroDesc: 'Empodere a su comunidad. Tome una foto, deje que la IA la clasifique y la asigne, y vea a los equipos municipales resolverla en tiempo récord.',
    reportBtn: 'Reportar Problema',
    checkStatus: 'Consultar Estado',
    nearbyIssues: 'Problemas Cercanos',
    heroStatsResolved: 'Problemas Resueltos',
    heroStatsActive: 'Reportes Activos',
    heroStatsSaved: 'Presupuesto Optimizado',
    step1: '1. Capture Foto',
    step2: '2. IA Detecta el Daño',
    step3: '3. Autoridades Reparan',
    step1Desc: 'Suba o tome una foto de la infraestructura dañada.',
    step2Desc: 'La IA de Gemini analiza el tipo, riesgo y asignación al instante.',
    step3Desc: 'Enviado automáticamente al departamento municipal correcto.',
    dashboard: 'Panel Principal',
    mapView: 'Mapa Interactivo',
    leaderboard: 'Clasificación',
    aiCopilot: 'Copiloto IA',
    municipality: 'Panel Municipal',
    activeUser: 'Perfil de Ciudadano Activo',
    xpPoints: 'XP de Héroe Cívico',
    badgesEarned: 'Medallas Obtenidas',
    reportNewIssue: 'Reportar Nuevo Problema',
    issueType: 'Clasificación de Daño',
    severity: 'Nivel de Gravedad',
    riskScore: 'Puntuación de Riesgo',
    department: 'Departamento Asignado',
    location: 'Ubicación Geográfica',
    explanation: 'Evaluación de IA',
    submitReport: 'Enviar Reporte Verificado',
    duplicateFound: '¡Sistema de prevención de duplicados activo!',
    duplicateMsg: 'Se detectó un problema similar a menos de 50 metros. ¡Sus datos se unieron para darle prioridad!',
    myReports: 'Mis Reportes de Daños',
    noReports: 'Aún no ha enviado reportes.',
    citizenFeedback: 'Verificaciones de la Comunidad',
    verifyThisIssue: 'Confirmar Problema',
    alreadyVerified: 'Ya confirmó este reporte',
    upvote: 'Votar Reporte',
    welcomeBack: '¡Bienvenido de nuevo, Héroe Cívico!',
    emergencyMode: 'ALERTA DE EMERGENCIA ACTIVA',
    emergencyDesc: 'Peligro crítico detectado. ¡Servicios de emergencia alertados al instante!',
    cityHealthScore: 'Puntuación de Salud de la Ciudad',
    copilotPlaceholder: 'Pregunte al copiloto: "¿Qué zonas son peligrosas?" o "¿Dónde se pronostican baches?"',
    copilotTitle: 'Copiloto Cívico Inteligente',
    copilotTagline: 'Consulte a la IA sobre zonas de riesgo y mantenimiento predictivo',
    predPotholes: 'Análisis de Infraestructura Predictiva',
    predFlood: 'Alertas de Zonas de Inundación por IA',
    predGarbage: 'Predicción de Acumulación de Desechos',
    officerDashboard: 'Rendimiento del Personal',
    averageFixTime: 'Tiempo Promedio de Reparación',
    activeTeams: 'Equipos Técnicos Activos',
    searchPlacePlaceholder: 'Buscar lugares en la India para reportar problemas...',
    searchBtn: 'Buscar',
    popularPlaces: 'Lugares Populares'
  },
  hi: {
    appName: 'Civic Taskforce AI',
    tagline: 'एआई-संचालित स्थानीय नागरिक समस्या निवारण एवं स्मार्ट शासन प्रणाली',
    heroTitle: 'एआई का उपयोग करके सेकंडों में नागरिक समस्याओं की रिपोर्ट करें',
    heroDesc: 'अपने समुदाय को सशक्त बनाएं। एक तस्वीर लें, एआई को वर्गीकरण करने दें और नगर पालिका टीम को रिकॉर्ड समय में इसका समाधान करते हुए देखें।',
    reportBtn: 'समस्या की रिपोर्ट करें',
    checkStatus: 'स्थिति की जांच करें',
    nearbyIssues: 'आस-पास की समस्याएं',
    heroStatsResolved: 'हल की गई समस्याएं',
    heroStatsActive: 'सक्रिय रिपोर्ट',
    heroStatsSaved: 'बजट अनुकूलन',
    step1: '1. फोटो खींचें',
    step2: '2. एआई समस्या की पहचान करेगा',
    step3: '3. अधिकारी ठीक करेंगे',
    step1Desc: 'नागरिक क्षति की एक छवि अपलोड करें या कैप्चर करें।',
    step2Desc: 'जेमिनी एआई तुरंत प्रकार, जोखिम और विभाग रूटिंग का विश्लेषण करता है।',
    step3Desc: 'त्वरित कार्रवाई के लिए सही नगरपालिका टीम को स्वचालित रूप से भेजा जाता है।',
    dashboard: 'डैशबोर्ड',
    mapView: 'इंटरैक्टिव मानचित्र',
    leaderboard: 'लीडरबोर्ड',
    aiCopilot: 'एआई कोपायलट चैट',
    municipality: 'नगरपालिका नियंत्रण कक्ष',
    activeUser: 'सक्रिय नागरिक प्रोफाइल',
    xpPoints: 'नागरिक नायक XP',
    badgesEarned: 'अर्जित बैज',
    reportNewIssue: 'नई नागरिक समस्या की रिपोर्ट करें',
    issueType: 'समस्या का वर्गीकरण',
    severity: 'तीव्रता का स्तर',
    riskScore: 'सार्वजनिक जोखिम स्कोर',
    department: 'विभाग रूटिंग',
    location: 'स्थान पिन करें',
    explanation: 'एआई मूल्यांकन टिप्पणियाँ',
    submitReport: 'सत्यापित रिपोर्ट सबमिट करें',
    duplicateFound: 'डुप्लिकेट रोकथाम प्रणाली सक्रिय!',
    duplicateMsg: '50 मीटर के भीतर पास में एक समान समस्या का पता चला था। इस समस्या को प्राथमिकता देने के लिए आपका विवरण मिला दिया गया है!',
    myReports: 'मेरी रिपोर्ट की गई समस्याएं',
    noReports: 'अभी तक कोई रिपोर्ट प्रस्तुत नहीं की गई है।',
    citizenFeedback: 'सामुदायिक सत्यापन',
    verifyThisIssue: 'समस्या का सत्यापन करें',
    alreadyVerified: 'आपने इस रिपोर्ट को सत्यापित किया है',
    upvote: 'रिपोर्ट को अपवोट करें',
    welcomeBack: 'वापसी पर स्वागत है, नागरिक नायक!',
    emergencyMode: 'आपातकालीन चेतावनी सक्रिय',
    emergencyDesc: 'अत्यंत गंभीर खतरा पाया गया। आपातकालीन सेवाओं को तुरंत सूचित कर दिया गया है!',
    cityHealthScore: 'शहर स्वास्थ्य स्कोर',
    copilotPlaceholder: 'कोपायलट से पूछें: "कौन सा क्षेत्र उच्च जोखिम वाला है?" या "बाढ़ का क्या पूर्वानुमान है?"',
    copilotTitle: 'नागरिक स्मार्ट कोपायलट',
    copilotTagline: 'जोखिम वाले क्षेत्रों, पूर्वानुमानित रखरखाव और शहर की रिपोर्टों के बारे में एआई से पूछें',
    predPotholes: 'पूर्वानुमानित बुनियादी ढांचा विश्लेषण',
    predFlood: 'एआई बाढ़ क्षेत्र अलर्ट',
    predGarbage: 'कचरा ओवरफ्लो पूर्वानुमान',
    officerDashboard: 'अधिकारी प्रदर्शन रेटिंग',
    averageFixTime: 'औसत समाधान समय',
    activeTeams: 'सक्रिय सेवा दल',
    searchPlacePlaceholder: 'समस्याओं की रिपोर्ट करने के लिए भारत में स्थान खोजें...',
    searchBtn: 'खोजें',
    popularPlaces: 'लोकप्रिय स्थान'
  },
  ja: {
    appName: 'Civic Taskforce AI',
    tagline: 'AI搭載地域密着型市民問題検出・解決＆スマート統治システム',
    heroTitle: 'AIを使って数秒で街の問題を報告',
    heroDesc: '地域社会をもっと住みやすく。写真を撮るだけでGemini AIが問題を自動分類・ルート決定。自治体チームによる迅速な解決を支援します。',
    reportBtn: '不具合を報告',
    checkStatus: 'ステータス確認',
    nearbyIssues: '周辺の問題',
    heroStatsResolved: '解決済みの問題',
    heroStatsActive: 'アクティブな報告',
    heroStatsSaved: '最適化された予算',
    step1: '1. 写真を撮影',
    step2: '2. AIが自動分析',
    step3: '3. 迅速なスピード修復',
    step1Desc: '破損箇所の写真を撮るかアップロードします。',
    step2Desc: 'Gemini AIが危険度、緊急性、担当部署を瞬時に特定します。',
    step3Desc: '適切な修理部門に自動通知され、速やかに解決へと動き出します。',
    dashboard: 'ダッシュボード',
    mapView: 'マップ表示',
    leaderboard: 'ランキング',
    aiCopilot: 'AIコパイロット',
    municipality: '自治体ダッシュボード',
    activeUser: '市民プロフィール',
    xpPoints: '市民ヒーローXP',
    badgesEarned: '獲得バッジ',
    reportNewIssue: '問題を新しく報告する',
    issueType: '不具合分類',
    severity: '深刻度レベル',
    riskScore: '市民リスクスコア',
    department: '担当部門',
    location: 'ピン位置',
    explanation: 'AI診断内容',
    submitReport: '確認報告を送信する',
    duplicateFound: '重複報告防止システム作動中！',
    duplicateMsg: '50メートル以内に類似した問題が既に報告されています。迅速な復旧のため、あなたの追加情報がマージされました。',
    myReports: '自分の報告履歴',
    noReports: '現在報告している問題はありません。',
    citizenFeedback: 'コミュニティでの確認',
    verifyThisIssue: 'この問題を裏付ける',
    alreadyVerified: '確認を登録済みです',
    upvote: '投票する',
    welcomeBack: 'おかえりなさい、市民ヒーロー！',
    emergencyMode: '緊急警報トリガー作動',
    emergencyDesc: '極めて危険な危険箇所が検出されました。緊急サービスに自動通報されました！',
    cityHealthScore: '都市健康度スコア',
    copilotPlaceholder: 'コパイロットに尋ねる:「どこが危険ゾーンですか？」や「道路破損の予測は？」',
    copilotTitle: '市民スマートコパイロット',
    copilotTagline: '危険地帯、予測メンテナンス、都市活動データをAIに尋ねる',
    predPotholes: 'インフラ破損の予測分析',
    predFlood: 'AI浸水予想アラート',
    predGarbage: 'ごみ蓄積予測アラート',
    officerDashboard: '職員パフォーマンス評価',
    averageFixTime: '平均解決時間',
    activeTeams: '稼働中のサービス作業班',
    searchPlacePlaceholder: '問題を報告するインドの場所を検索...',
    searchBtn: '検索',
    popularPlaces: '人気の場所'
  },
  mr: {
    appName: 'सिव्हिक टास्कफोर्स एआय',
    tagline: 'एआय-चालित स्थानिक नागरी समस्या शोध, निवारण आणि स्मार्ट शासन प्रणाली',
    heroTitle: 'एआय च्या मदतीने काही सेकंदात नागरी समस्यांची नोंद करा',
    heroDesc: 'तुमच्या समुदायाला सक्षम करा. एक फोटो काढा, एआय ला समस्येचे वर्गीकरण आणि योग्य विभागाकडे पाठवू द्या, आणि महानगरपालिका टीमला ते विक्रमी वेळेत सोडवताना पहा.',
    reportBtn: 'समस्या नोंदवा',
    checkStatus: 'स्थिती तपासा',
    nearbyIssues: 'जवळपासच्या समस्या',
    heroStatsResolved: 'सोडवलेल्या समस्या',
    heroStatsActive: 'सक्रिय अहवाल',
    heroStatsSaved: 'बजेट ऑप्टिमायझेशन्स',
    step1: '१. फोटो काढा',
    step2: '२. एआय समस्या शोधेल',
    step3: '३. प्रशासन दुरुस्त करेल',
    step1Desc: 'नागरी नुकसानीचा फोटो अपलोड किंवा कॅप्चर करा.',
    step2Desc: 'जेमिनी एआय लगेच समस्येचा प्रकार, धोका आणि संबंधित विभागाचा अंदाज लावेल.',
    step3Desc: 'त्वरित कारवाईसाठी स्वयंचलितपणे योग्य महानगरपालिका टीमकडे पाठवले जाईल.',
    dashboard: 'डॅशबोर्ड',
    mapView: 'परस्परसंवादी नकाशा',
    leaderboard: 'लीडरबोर्ड',
    aiCopilot: 'एआय कोपायलट चॅट',
    municipality: 'महानगरपालिका नियंत्रण कक्ष',
    activeUser: 'सक्रिय नागरिक प्रोफाइल',
    xpPoints: 'नागरी हिरो XP',
    badgesEarned: 'कमावलेले बॅजेस',
    reportNewIssue: 'नवीन नागरी समस्येची नोंद करा',
    issueType: 'समस्या वर्गीकरण',
    severity: 'तीव्रतेची पातळी',
    riskScore: 'सार्वजनिक धोका स्कोअर',
    department: 'संबंधित विभाग',
    location: 'स्थान पिन करा',
    explanation: 'एआय मूल्यमापन नोंदी',
    submitReport: 'सत्यापित अहवाल सबमिट करा',
    duplicateFound: 'डुप्लिकेट प्रतिबंध प्रणाली सक्रिय!',
    duplicateMsg: '५० मीटरच्या आत अशीच समस्या आढळली आहे. या समस्येला प्राधान्य देण्यासाठी तुमची माहिती मर्च केली आहे!',
    myReports: 'माझ्या नोंदवलेल्या समस्या',
    noReports: 'अद्याप एकही अहवाल सबमिट केला नाही.',
    citizenFeedback: 'समुदाय पडताळणी',
    verifyThisIssue: 'समस्येची पडताळणी करा',
    alreadyVerified: 'तुम्ही या अहवालाची पडताळणी केली आहे',
    upvote: 'अहवालाला मत द्या',
    welcomeBack: 'परत स्वागत आहे, नागरी हिरो!',
    emergencyMode: 'आणीबाणी चेतावणी सक्रिय',
    emergencyDesc: 'अतिशय गंभीर धोका आढळला. आणीबाणी सेवांना त्वरित स्वयंचलित सूचित केले आहे!',
    cityHealthScore: 'शहर आरोग्य स्कोअर',
    copilotPlaceholder: 'कोपायलटला विचारा: "कोणता परिसर जास्त धोक्याचा आहे?" किंवा "पूराचा अंदाज काय आहे?"',
    copilotTitle: 'नागरी स्मार्ट कोपायलट',
    copilotTagline: 'धोकादायक क्षेत्रे, प्रतिबंधात्मक देखभाल आणि शहराच्या अहवालांबद्दल एआय ला विचारा',
    predPotholes: 'भविष्यातील पायाभूत सुविधांचे विश्लेषण',
    predFlood: 'एआय पूर क्षेत्र इशारे',
    predGarbage: 'कचरा ओव्हरफ्लो अंदाज',
    officerDashboard: 'अधिकारी कामगिरी रेटिंग',
    averageFixTime: 'सरासरी निराकरण वेळ',
    activeTeams: 'सक्रिय सेवा पथके',
    searchPlacePlaceholder: 'समस्या नोंदवण्यासाठी भारतातील ठिकाणे शोधा...',
    searchBtn: 'शोधा',
    popularPlaces: 'लोकप्रिय ठिकाणे'
  }
};
